In [ ]:
Rating = 
israted = 

HasRole = 
HasGenre = 

In [2]:
from sklearn import linear_model
import numpy as np

In [9]:
lm = linear_model.LinearRegression(fit_intercept=False)
X = np.array([[1, 1], [1, 2], [1, 3]])
x = np.array([1, 2, 3]).reshape(-1, 1)
y = np.array([1.1, 2.9, 5])
lm.fit(X, y)
lm.coef_
# lm.intercept_

array([-0.9 ,  1.95])

In [10]:
lm = linear_model.LinearRegression(fit_intercept=False)
X = np.array([[1, 0.148, 0.221], [1, 0.697, 0.895], [1, 0.663, 0.774]])
x = np.array([1, 2, 3]).reshape(-1, 1)
y = np.array([2.7, 1.9, 2.1])
lm.fit(X, y)
lm.coef_

array([ 2.99027187,  0.87330223, -1.89828327])

In [17]:
x = np.array([1, 3, 5])
y = np.array([5, 29, 77])
X = x**2 + 1
X = np.array([[1, 2], [1, 10], [1, 26]])
lm.fit(X, y)
lm.coef_

array([0., 3.])

In [19]:
x = np.array([1, 3, 5])
y = np.array([5, 29, 77])
X = x**2 + 1
3*np.sum(np.multiply(X, y)) - np.sum(X) * np.sum(y)
2688/(3*np.sum(np.power(X, 2)) - np.power(np.sum(X), 2))

3.0

In [16]:
x = np.array([[0.3,0.4], [0.7,0.1], [1.0,1.5]])
y = np.array([3.2, 3.9, 3.5])
w0 = 1
w = np.array([1, 1])
y_ = np.matmul(x, w.T) + w0
MSE = 1/3 * np.sum(np.power(y - y_, 2))
MSE

2.22

In [15]:
x = np.array([[0.3,0.4], [0.7,0.1], [1.0,1.5]])
y = np.array([3.2, 3.9, 3.5])
w0 = 2.35
w = np.array([1.35, 0.20])
y_ = np.matmul(x, w.T) + w0
MSE = 1/3 * np.sum(np.power(y - y_, 2))
MSE

0.2418166666666667

In [17]:
x = np.array([[0.3,0.4], [0.7,0.1], [1.0,1.5]])
y = np.array([3.2, 3.9, 3.5])
w0 = 0.90
w = np.array([0.90, 0.90])
y_ = np.matmul(x, w.T) + w0
MSE = 1/3 * np.sum(np.power(y - y_, 2))
MSE

2.7032666666666665