In [7]:
%load_ext autoreload
%autoreload 2
import numpy as np
from sklearn.metrics import accuracy_score, precision_score
import sys
sys.path.append('../')
from utils import invert, to_dense, sum

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [4]:
scores = np.array([23,4,4, 5,24])
indices = np.array([1,2,3,4])

np.flip(np.argsort(scores)).astype(int)

array([4, 0, 3, 2, 1])

In [22]:
np.argsort(scores)[::-1]

array([2, 3, 0, 1], dtype=int64)

In [52]:
import numpy as np
from scipy.sparse import csr_matrix, lil_matrix
 
# Defining the array
x = np.arange(35).reshape(7, 5)
x = csr_matrix(x)

In [53]:
x.toarray() ** 2

array([[   0,    1,    4,    9,   16],
       [  25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196],
       [ 225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576],
       [ 625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156]], dtype=int32)

In [32]:
y = x.copy()
y[:1] = 0
y.toarray()

c:\Users\nieht\Anaconda3\envs\cornac\lib\site-packages\scipy\sparse\_index.py:146: SparseEfficiencyWarning: Changing the sparsity structure of a csr_matrix is expensive. lil_matrix is more efficient.
  self._set_arrayXarray(i, j, x)


array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 1, 0, 0, 0]], dtype=int32)

In [51]:
np.sqrt(np.max(x, axis=1)).toarray().flatten()

array([1., 1., 1., 1., 1., 1., 1.])

In [3]:
def bool_to_index(x):
    bool_array = to_dense(x, squeeze=True).astype(bool)
    print(bool_array)
    idx = np.arange(len(bool_array))
    idx = idx[bool_array]
    print(idx)
    return idx

In [4]:
a = (x.sum(1) > 100).astype(int)
bool_to_index(a)

[False False False False  True  True  True]
[4 5 6]


array([4, 5, 6])

In [7]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [5]:
a

matrix([[0],
        [0],
        [0],
        [0],
        [1],
        [1],
        [1]])

In [92]:
to_dense(a, squeeze=True)

matrix([[0, 1, 0, 0, 1, 1, 1]])

In [91]:
type(to_dense(a, squeeze=True).astype(bool))

numpy.matrix