In [1]:
%load_ext autoreload
%autoreload 2
import numpy as np
from sklearn.metrics import accuracy_score, precision_score
y_pred = [0, 0, 1, 1]
y_true = [0, 1, 0, 1]
accuracy_score(y_true, y_pred)
precision_score(y_true, y_pred)

0.5

In [5]:
i = 2
n = 4
idx = np.array([j for j in range(n) if i != j]).astype(int)
# y_pred[idx]
idx

array([0, 1, 3])

In [17]:
import numpy as geek
from scipy.sparse import csr_matrix, lil_matrix
 
# Defining the array
x = geek.arange(35).reshape(7, 5)
x = csr_matrix(x)
 
# print(geek.delete(x, 3, axis=0))
idx = np.array([1,3,4,5])
x = x[idx].toarray()
x

array([[ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]], dtype=int32)

In [8]:
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [17]:
import sys
sys.path.append('../')
from utils import get_metrics